name: kopuro
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.4
  flutter_launcher_icons: ^0.13.1
  flutter_bloc: ^8.1.3
  intro_slider: ^4.2.1
  json_annotation: ^4.8.1
  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  equatable: ^2.0.5
  google_fonts: ^6.1.0
  cloud_firestore: ^4.12.2
  image_picker: ^1.0.4
  firebase_storage: ^11.5.0
  formz: ^0.7.0
  flow_builder: ^0.0.10
  flutter_svg: ^2.0.9
  intl: any
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/

  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

